server:
  port: 9101

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: CWS
    password: admin123
    driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      hibernate:
        ddl-auto: UPDATE
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.Oracle12cDialect

spring-doc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    docExpansion: none
    showExtensions: true
    showCommonExtensions: true
    filter: true
    displayOperationId: true
    displayRequestDuration: true